#!/bin/sh -e
# initramfs hook for etherwake


PREREQ=""

# Output pre-requisites
prereqs()
{
	echo "$PREREQ"
}

case "$1" in
    prereqs)
	prereqs
	exit 0
	;;
esac


. /usr/share/initramfs-tools/hook-functions


# Copy across the binaries
copy_exec /usr/sbin/etherwake /sbin

